### ISSUE TITLE
Pally and Kronos elite skill req

### ISSUE THREAD

**Issue by reepotah** [the-outuni-project/legacy-waitlist#38]
Only Turret 4 is currently required for Pally and Kronos Elite skill set, which is impossible alongside Spec 4 ofc.
![изображение](https://github.com/the-outuni-project/legacy-waitlist/assets/45051999/3b6f0aa1-cd5f-47f4-9047-dbac69488c1a)
![изображение](https://github.com/the-outuni-project/legacy-waitlist/assets/45051999/570a87a4-7af2-40f6-a091-d828b957052c)

**Comment by wesleygroen** [comment]
#39 should solve that
